name: Test glossary2 for TYPO3 11 LTS

on:
  pull_request:

jobs:
  CGL:
    name: Coding Style Check (TYPO3 Community CGL)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s composerUpdate

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s lint

      - name: Validate code against CGL
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s cgl -n

  testsuite:
    name: PHP Unit and Functional Tests for TYPO3 Version 11 LTS

    needs: CGL

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 11 -s composerUpdate

      - name: Unit Tests
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s unit

      - name: Functional tests with mariadb
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -d mariadb -s functional

      - name: Functional tests with sqlite
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -d sqlite -s functional
